name: Build Shared Library on Linux

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl     # Default 64-bit
          - i686-unknown-linux-musl       # 32-bit
          - aarch64-unknown-linux-musl    # ARM64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Cross Dependencies
        run: |
          sudo apt-get update
          sudo apt install musl-tools
          cargo install cross

      - name: Install Cross Dependencies
        run: |
          sudo apt-get update
          if [ "${{ matrix.target }}" = "i686-unknown-linux-musl" ]; then
            sudo apt-get install gcc-multilib
          elif [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
            sudo apt-get install gcc-aarch64-linux-musl
            echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-musl-gcc" >> $GITHUB_ENV
          fi

      - name: Build Shared Library
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename .so to target-specific name
        run: |
          mv target/${{ matrix.target }}/release/lib*.so target/${{ matrix.target }}/release/chlaty-lib-hianime-${{ matrix.target }}.so


      - name: Upload .so Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-chlaty-lib-hianime-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/chlaty-lib-hianime-${{ matrix.target }}.so
