name: Build Shared Library on Linux

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Shared Library
        run: cargo build --release

      - name: Upload .so Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-so
          path: target/release/lib*.so
