name: Build Dylib on macOS

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin     # Intel Macs
          - aarch64-apple-darwin    # Apple Silicon

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build Dylib
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload .dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dylib-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/lib*.dylib
