name: Build Dylib on macOS

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin     # Intel Macs
          - aarch64-apple-darwin    # Apple Silicon

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build Dylib
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename .dylib to target-specific name
        run: |
          mv target/${{ matrix.target }}/release/lib*.dylib target/${{ matrix.target }}/release/${{ matrix.target }}.dylib


      - name: Upload .dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.target }}.dylib
