name: Build Dylib on macOS

on:
  push:
    branches: [build]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Dylib
        run: cargo build --release

      - name: Upload .dylib Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dylib
          path: target/release/lib*.dylib
