name: Build DLL on Windows

on:
  push:
    branches: [build]
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build DLL
        run: cargo build --release

      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dll
          path: target/release/*.dll
