name: Build DLL on Windows

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build-windows:
    
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc     # 64-bit
          - i686-pc-windows-msvc       # 32-bit
          - aarch64-pc-windows-msvc    # ARM64
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust and Target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Install Cross Dependencies
        run: |
          cargo install cross

      - name: Build DLL
        run: cross build --release --target ${{ matrix.target }}

      - name: Rename .dll to target-specific name
        run: |
          $source = Get-ChildItem -Path "target/${{ matrix.target }}/release/" -Filter *.dll | Select-Object -First 1
          $destination = Join-Path -Path $source.DirectoryName -ChildPath "chlaty-lib-hianime-${{ matrix.target }}.dll"
          Rename-Item -Path $source.FullName -NewName $destination


      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-chlaty-lib-hianime-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/chlaty-lib-hianime-${{ matrix.target }}.dll

